package Main;

import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo & Legion
 */
public class RegisterForm extends javax.swing.JFrame {
    
    DBDataUser UserData;
    
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIcon();
    }
    
    /**
     * set app icon
     */
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/wizard.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        closeMinPanel = new javax.swing.JPanel();
        clloseButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        fullnameLabel = new javax.swing.JLabel();
        fullnameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameFIeld = new javax.swing.JTextField();
        pwLabel = new javax.swing.JLabel();
        pwField = new javax.swing.JPasswordField();
        pwConfirmLabel = new javax.swing.JLabel();
        pwConfirmField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Login.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        Login.setText("Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Login)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(364, 480));
        setUndecorated(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(364, 480));
        jPanel1.setLayout(null);

        closeMinPanel.setBackground(new java.awt.Color(204, 204, 255));
        closeMinPanel.setBorder(new javax.swing.border.MatteBorder(null));

        clloseButton.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        clloseButton.setForeground(new java.awt.Color(255, 255, 255));
        clloseButton.setText("X");
        clloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clloseButtonMouseClicked(evt);
            }
        });

        minimizeButton.setFont(new java.awt.Font("Book Antiqua", 1, 48)); // NOI18N
        minimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        minimizeButton.setText("-");
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closeMinPanelLayout = new javax.swing.GroupLayout(closeMinPanel);
        closeMinPanel.setLayout(closeMinPanelLayout);
        closeMinPanelLayout.setHorizontalGroup(
            closeMinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeMinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        closeMinPanelLayout.setVerticalGroup(
            closeMinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeMinPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(closeMinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clloseButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel1.add(closeMinPanel);
        closeMinPanel.setBounds(290, 0, 0, 30);

        registerLabel.setBackground(new java.awt.Color(204, 204, 255));
        registerLabel.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel.setText("Register");
        jPanel1.add(registerLabel);
        registerLabel.setBounds(10, 10, 95, 32);

        fullnameLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        fullnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        fullnameLabel.setText("Full Name");
        fullnameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(fullnameLabel);
        fullnameLabel.setBounds(70, 150, 80, 30);

        fullnameField.setBackground(new java.awt.Color(204, 204, 255));
        fullnameField.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jPanel1.add(fullnameField);
        fullnameField.setBounds(180, 150, 160, 30);

        usernameLabel.setBackground(new java.awt.Color(0, 0, 0));
        usernameLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username");
        usernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(usernameLabel);
        usernameLabel.setBounds(70, 200, 71, 30);

        usernameFIeld.setBackground(new java.awt.Color(204, 204, 255));
        usernameFIeld.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jPanel1.add(usernameFIeld);
        usernameFIeld.setBounds(180, 200, 160, 30);

        pwLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        pwLabel.setForeground(new java.awt.Color(255, 255, 255));
        pwLabel.setText("Password");
        jPanel1.add(pwLabel);
        pwLabel.setBounds(70, 250, 68, 30);

        pwField.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(pwField);
        pwField.setBounds(180, 250, 160, 30);

        pwConfirmLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        pwConfirmLabel.setForeground(new java.awt.Color(255, 255, 255));
        pwConfirmLabel.setText("Confirm Password");
        pwConfirmLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(pwConfirmLabel);
        pwConfirmLabel.setBounds(40, 300, 127, 30);

        pwConfirmField.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(pwConfirmField);
        pwConfirmField.setBounds(180, 300, 160, 30);

        registerButton.setBackground(new java.awt.Color(102, 102, 255));
        registerButton.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setBorder(new javax.swing.border.MatteBorder(null));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton);
        registerButton.setBounds(80, 420, 90, 20);

        cancelButton.setBackground(new java.awt.Color(255, 102, 102));
        cancelButton.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setBorder(new javax.swing.border.MatteBorder(null));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton);
        cancelButton.setBounds(190, 420, 90, 20);

        background.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgroundSnow.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 364, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clloseButtonMouseClicked
        try {
            DBCommunication.DBDisconnect();
        } catch (SQLException ex) {
            Logger.getLogger(GameplayUserHomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_clloseButtonMouseClicked

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String fname = fullnameField.getText();
        String uname = usernameFIeld.getText();
        String pass1 = String.valueOf(pwField.getPassword());
        String pass2 = String.valueOf(pwConfirmField.getPassword());
        String aux;
        
        UserData = new DBDataUser();
        UserData.setUsername(uname);
        
        if( verifyFields(fname,uname,pass1,pass2) ){
            aux = UserData.doRegistration(fname,pass1);
            System.out.println(aux);
            if( "sucess".equals(aux) ){
                    JOptionPane.showMessageDialog(null, "Your account has been created!");
                    WelcomeForm mnf = new WelcomeForm();
                    mnf.setVisible(true);
                    mnf.pack();
                    mnf.setLocationRelativeTo(null);
                    this.dispose();
            }
            if( "error-reg".equals(aux) ){
                JOptionPane.showMessageDialog(null, "Error: Check your information");
            }  
            if( "error-username".equals(aux) ){
                JOptionPane.showMessageDialog(null, "this username is already taken!", "Username Failed",2);
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        Login lgf = new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    public boolean verifyFields(String uname, String fname , String p1 , String p2){
        if ((fname.trim().equals("")) || (uname.trim().equals("")) ||(p1.trim().equals(""))|| (p2.trim().equals(""))){
            JOptionPane.showMessageDialog(null, "One or more fields are empty!");
            return false;
        }
        else if (!p1.equals(p2)){
            JOptionPane.showMessageDialog(null, "Password doesn't match!", "Confirm password", 2);
            return false;
        }
        else{
            return true;
        }
    }
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel clloseButton;
    private javax.swing.JPanel closeMinPanel;
    private javax.swing.JTextField fullnameField;
    private javax.swing.JLabel fullnameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JPasswordField pwConfirmField;
    private javax.swing.JLabel pwConfirmLabel;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JLabel pwLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JTextField usernameFIeld;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
