package Main;


import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;


/**
 *
 * @author Gustavo
 */
public class TutorialForm extends javax.swing.JFrame {

    
    private final String user , Quest , Class;
    private String Location;
    private int buttonPressedNo=0;
    DBDataUser UserData;
    
    /**
     * Creates new form TutorialForm
     */
    public TutorialForm() {
        UserData = new DBDataUser();
        UserData.setDataUser();
        this.user = UserData.getUsername();
        this.Quest = UserData.getUserQuest();
        this.Class = UserData.getUserClass();
        
        initComponents();
        setIcon(); 
        setInitialVisuals();
        setWizWelcome();
    }
    
    /**
     * sets the location to the class that call TutorialForm
     * @param Location 
     */
    public void setLocation(String Location){
        this.Location = Location;
    }
    
    /**
     * sets the welcome speach of the wizard according to the location that the users comes from
     */
    private void setWizWelcome() {
        if ("fitness".equals(Quest)) wizSpeach.setText("<html> Welcome to the Fighters Guild! Here I will train you to achieve your fitness goal and become a healthier warrior!<html>");
        if ("academic".equals(Quest)) wizSpeach.setText("<html> Welcome the College of Wizardry and Science! Here you will learn from a greatest mind how to achieve academic success!<html>");
        if ("mind".equals(Quest)) wizSpeach.setText("<html> Welcome to the Arcane Order of the Mind! All the wisemen from our world gather here to seek peace and share their teachings.<html>");
    }
    
    /**
     * sets the inital visibility for labels/buttons and images
     */
    private void setInitialVisuals(){
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/"+this.Quest+"Center.png")));
        userLabel.setVisible(false);
        userInfoPanel.setVisible(false);
        userButton.setVisible(false);
        wizHouseButton.setVisible(false); 
        catalfButton.setVisible(false);
    }
    
    /**
     * set app icon
     */
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/wizard.png"))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeMinPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        wizImg = new javax.swing.JLabel();
        wizSpeach = new javax.swing.JLabel();
        wizBallon = new javax.swing.JLabel();
        catalfButton = new javax.swing.JButton();
        wizHouseButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        userInfoPanel = new javax.swing.JPanel();
        mushieImg = new javax.swing.JLabel();
        knowledgeLabel = new javax.swing.JLabel();
        coinImg = new javax.swing.JLabel();
        coinLabel = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        closeMinPanel.setBackground(new java.awt.Color(153, 102, 0));
        closeMinPanel.setBorder(new javax.swing.border.MatteBorder(null));

        closeButton.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        minimizeButton.setFont(new java.awt.Font("Book Antiqua", 1, 48)); // NOI18N
        minimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        minimizeButton.setText("-");
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closeMinPanelLayout = new javax.swing.GroupLayout(closeMinPanel);
        closeMinPanel.setLayout(closeMinPanelLayout);
        closeMinPanelLayout.setHorizontalGroup(
            closeMinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeMinPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        closeMinPanelLayout.setVerticalGroup(
            closeMinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeMinPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(closeMinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(closeMinPanel);
        closeMinPanel.setBounds(620, 0, 80, 30);

        wizImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wizard2.png"))); // NOI18N
        jPanel1.add(wizImg);
        wizImg.setBounds(20, 60, 120, 130);

        wizSpeach.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jPanel1.add(wizSpeach);
        wizSpeach.setBounds(200, 30, 280, 80);

        wizBallon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/balloon3.png"))); // NOI18N
        jPanel1.add(wizBallon);
        wizBallon.setBounds(160, 10, 370, 130);

        catalfButton.setBackground(new java.awt.Color(204, 102, 255));
        catalfButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        catalfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Catalf.png"))); // NOI18N
        catalfButton.setBorder(new javax.swing.border.MatteBorder(null));
        catalfButton.setContentAreaFilled(false);
        jPanel1.add(catalfButton);
        catalfButton.setBounds(520, 70, 160, 130);

        wizHouseButton.setBackground(new java.awt.Color(170, 63, 7));
        wizHouseButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        wizHouseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon.png"))); // NOI18N
        wizHouseButton.setBorder(new javax.swing.border.MatteBorder(null));
        wizHouseButton.setContentAreaFilled(false);
        jPanel1.add(wizHouseButton);
        wizHouseButton.setBounds(510, 300, 160, 150);

        userButton.setBorder(new javax.swing.border.MatteBorder(null));
        userButton.setContentAreaFilled(false);
        jPanel1.add(userButton);
        userButton.setBounds(20, 290, 120, 130);

        userLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setBorder(new javax.swing.border.MatteBorder(null));
        userLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(userLabel);
        userLabel.setBounds(30, 420, 120, 30);

        userInfoPanel.setBackground(new java.awt.Color(255, 255, 204));
        userInfoPanel.setBorder(new javax.swing.border.MatteBorder(null));
        userInfoPanel.setOpaque(false);

        mushieImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mushies_stage1.png"))); // NOI18N

        knowledgeLabel.setBackground(new java.awt.Color(255, 204, 51));
        knowledgeLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        knowledgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        knowledgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        coinImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coin.png"))); // NOI18N

        coinLabel.setBackground(new java.awt.Color(255, 204, 51));
        coinLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        coinLabel.setForeground(new java.awt.Color(255, 255, 255));
        coinLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coinImg, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(knowledgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mushieImg)
                .addGap(40, 40, 40))
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mushieImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coinImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(coinLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(knowledgeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(userInfoPanel);
        userInfoPanel.setBounds(10, 450, 140, 40);

        continueButton.setBackground(new java.awt.Color(255, 255, 255));
        continueButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        continueButton.setForeground(new java.awt.Color(0,0,0));
        continueButton.setText("Continue");
        continueButton.setBorder(new javax.swing.border.MatteBorder(null));
        continueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueButtonMouseClicked(evt);
            }
        });
        jPanel1.add(continueButton);
        continueButton.setBounds(220, 413, 220, 30);

        background.setBackground(new java.awt.Color(255, 255, 51));
        background.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 700, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        try {
            DBCommunication.DBDisconnect();
        } catch (SQLException ex) {
            Logger.getLogger(GameplayUserHomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void continueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueButtonMouseClicked
        if( ("register".equals(this.Location)) == true ){   
            switch (buttonPressedNo) {
                case 0:
                    wizSpeach.setText("<html>Now i'm going to give you a quick guide of your Home! <html>");
                    buttonPressedNo++;
                    break;
                case 1:
                    wizSpeach.setText("<html>Here you can see your character. By clicking in it you get acess to the challenges you completed and the items you bought, your backpack!<html>");
                    
                    userButton.setEnabled(false);
                    userButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/"+this.Class+"2.png")));
                    userButton.setVisible(true);
                    
                    userLabel.setText(this.user+" the "+this.Class);
                    userLabel.setVisible(true);
                    
                    userInfoPanel.setVisible(true);
                    
                    buttonPressedNo++;
                    break;
                case 2:
                    wizSpeach.setText("<html>Right about bellow you get to know how much coins and wisdom points you have!<html>");
                    userInfoPanel.setVisible(true);
                case 3:
                    wizSpeach.setText("<html>Now let me introduce to you Voiello, my loved cat. Well its a frame of him, he is over my house taking a nap or doing some cat stuff. You will get a chance to meet him.<html>");
                    
                    catalfButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Catalf.png"))); 
                    catalfButton.setEnabled(false);
                    catalfButton.setVisible(true);
                   
                    buttonPressedNo++;
                    break;
                case 4:
                    wizSpeach.setText("<html>As he is my kittie he has some psychic powers. You can summon him if you ever want to check out how other adventurers's quests are going!<html>");
                    buttonPressedNo++;
                    break;
                case 5:
                    wizSpeach.setText("<html>Time for you to know Ocapse, my travel's companion buddy. Whenever you want to give a good use for your coins, ask him for a ride. I will receive you with all the honor and love!<html>");
                    
                    wizHouseButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dragon.png"))); 
                    wizHouseButton.setEnabled(false);
                    wizHouseButton.setVisible(true);
                    
                    buttonPressedNo++;
                    break;
                case 6:
                    wizSpeach.setText("<html> And for the challenges that you will face, press the big red button! <html>");
                    buttonPressedNo++;
                    break;
                case 7:
                    wizSpeach.setText("<html>That's it! Are you ready to start this great adventure? <html>");
                    continueButton.setText("Let's start!");
                    buttonPressedNo++;
                    break;
                case 8:
                    GameplayUserHomeForm.setLocation("register");
                    GameplayUserHomeForm gmf = new GameplayUserHomeForm();
                    gmf.setVisible(true);
                    gmf.pack();
                    gmf.setLocationRelativeTo(null);
                    this.dispose();
                    break;
                default:
                    break;
            }
        }
        
        if( "newAdventure".equals(this.Location) == true ) { 
            switch (buttonPressedNo) {
                case 0:
                    wizSpeach.setText("<html>Time for a new fresh adventure!<html>");
                    
                    userButton.setEnabled(false);
                    userButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/"+this.Class+"2.png")));
                    userButton.setVisible(true);
                    
                    userLabel.setText(this.user+" the "+this.Class);
                    userLabel.setVisible(true);
                    
                    userInfoPanel.setVisible(true);
                    
                    catalfButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Catalf.png"))); 
                    catalfButton.setEnabled(false);
                    catalfButton.setVisible(true);
                    
                    wizHouseButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dragon.png"))); 
                    wizHouseButton.setEnabled(false);
                    wizHouseButton.setVisible(true);
                    
                    buttonPressedNo++;
                    break;
                case 1:
                    wizSpeach.setText("<html>As always let's go with the flow!<html>");
                    continueButton.setText("Let's start!");
                    buttonPressedNo++;
                    break;
                case 2:
                    System.out.println("location.tutorial"+Location);
                    GameplayUserHomeForm.Location = Location;
                    GameplayUserHomeForm gmf = new GameplayUserHomeForm();
                    gmf.setVisible(true);
                    gmf.pack();
                    gmf.setLocationRelativeTo(null);
                    this.dispose();
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_continueButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TutorialForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton catalfButton;
    private javax.swing.JLabel closeButton;
    private javax.swing.JPanel closeMinPanel;
    private javax.swing.JLabel coinImg;
    private javax.swing.JLabel coinLabel;
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel knowledgeLabel;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JLabel mushieImg;
    private javax.swing.JButton userButton;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel wizBallon;
    private javax.swing.JButton wizHouseButton;
    private javax.swing.JLabel wizImg;
    private javax.swing.JLabel wizSpeach;
    // End of variables declaration//GEN-END:variables
}
