/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class AdventureSelection extends javax.swing.JFrame {

    /**
     * Creates new form AdventureSelection
     */
    private int buttonPressedNo;    
    private String user;
    private String password;
    private String Quest;
    private String Class;
    
    public AdventureSelection() {
        initComponents();
        jLabelSwordAndShield.setVisible(false);
        jLabelBook.setVisible(false);
        jLabelHeart.setVisible(false);
        jButtonFitness.setVisible(false);
        jButtonAcademic.setVisible(false);
        jButtonMind.setVisible(false);
        setIcon();
        
    }
    public void passData(String user, String Class) {
        this.user = user;
        this.Class = Class;
        }
         public void setIcon()
    {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/wizard.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabeltext = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CloseButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        jLabelSwordAndShield = new javax.swing.JLabel();
        jLabelBook = new javax.swing.JLabel();
        jLabelHeart = new javax.swing.JLabel();
        jButtonContinue = new javax.swing.JButton();
        jButtonFitness = new javax.swing.JButton();
        jButtonAcademic = new javax.swing.JButton();
        jButtonMind = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wizard2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 120, 130);

        jLabeltext.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabeltext.setText("<html>As any great hero, you need a quest! <html>");
        jPanel1.add(jLabeltext);
        jLabeltext.setBounds(190, 20, 160, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/balloon22.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 0, 240, 130);

        jPanel3.setBackground(new java.awt.Color(153, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CloseButton.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        CloseButton.setText("X");
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });

        MinimizeButton.setFont(new java.awt.Font("Book Antiqua", 1, 48)); // NOI18N
        MinimizeButton.setText("-");
        MinimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinimizeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(500, 0, 60, 30);

        jLabelSwordAndShield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SwordAndShield.png"))); // NOI18N
        jPanel1.add(jLabelSwordAndShield);
        jLabelSwordAndShield.setBounds(20, 130, 150, 140);

        jLabelBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book.png"))); // NOI18N
        jPanel1.add(jLabelBook);
        jLabelBook.setBounds(210, 150, 130, 120);

        jLabelHeart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/heart.png"))); // NOI18N
        jPanel1.add(jLabelHeart);
        jLabelHeart.setBounds(380, 150, 130, 120);

        jButtonContinue.setBackground(new java.awt.Color(153, 153, 255));
        jButtonContinue.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jButtonContinue.setText("Continue");
        jButtonContinue.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContinueMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonContinue);
        jButtonContinue.setBounds(140, 350, 250, 30);

        jButtonFitness.setBackground(new java.awt.Color(255, 51, 51));
        jButtonFitness.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jButtonFitness.setText("<html>Improve Fitness <html>");
        jButtonFitness.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFitness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFitnessMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonFitness);
        jButtonFitness.setBounds(60, 290, 80, 40);

        jButtonAcademic.setBackground(new java.awt.Color(51, 153, 255));
        jButtonAcademic.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jButtonAcademic.setText("<html>Improve Academic  Performance<html>");
        jButtonAcademic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAcademic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAcademicMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonAcademic);
        jButtonAcademic.setBounds(230, 280, 100, 50);

        jButtonMind.setBackground(new java.awt.Color(102, 255, 102));
        jButtonMind.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jButtonMind.setText("<html>Achieve Peace of Mind<html>");
        jButtonMind.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMindMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonMind);
        jButtonMind.setBounds(410, 280, 80, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tavern.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 410);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void MinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonMouseClicked

    private void jButtonContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinueMouseClicked
        // TODO add your handling code here:
        buttonPressedNo ++;
        if (buttonPressedNo==1)
        {
            jLabeltext.setText("<html>What type of adventure are you after? <html>");
            jLabelSwordAndShield.setVisible(true);
            jLabelBook.setVisible(true);
            jLabelHeart.setVisible(true);
            jButtonFitness.setVisible(true);
            jButtonAcademic.setVisible(true);
            jButtonMind.setVisible(true);
            jButtonContinue.setVisible(false);

        }
        if(buttonPressedNo == 3)
        {
                TutorialForm ttf = new TutorialForm();
                ttf.setVisible(true);
                ttf.pack();
                ttf.setLocationRelativeTo(null);
                ttf.passData(user, this.Quest ,Class);
                this.dispose();    
        }


    }//GEN-LAST:event_jButtonContinueMouseClicked

    private void jButtonFitnessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFitnessMouseClicked
        // TODO add your handling code here:

        PreparedStatement ps;
        ResultSet rs;
        String username = this.user;
        System.out.println(username);
                  
        String query = "UPDATE `users` SET `Quest`= ? WHERE `username` = ?";       
        
        try {
            
            ps = My_CNX.getConnection().prepareStatement(query);
            ps.setString(1, "fitness");
            ps.setString(2, username);
            if(ps.executeUpdate()!=0)
                    {
                        JOptionPane.showMessageDialog(null, "Quest selected!");                          
                          
                    }
             
        } catch (SQLException ex) {
            Logger.getLogger(BasicsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
           this.Quest= "fitness";
           buttonPressedNo ++;
        if (buttonPressedNo==2){
            jLabeltext.setText("<html>Let's start! <html>");
            jLabelSwordAndShield.setVisible(true);
            jLabelBook.setVisible(false);
            jLabelHeart.setVisible(false);
            jButtonFitness.setVisible(false);
            jButtonAcademic.setVisible(false);
            jButtonMind.setVisible(false);
            jButtonContinue.setVisible(true);

        }
       

    }//GEN-LAST:event_jButtonFitnessMouseClicked

    private void jButtonAcademicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAcademicMouseClicked
        try {                                             
            // TODO add your handling code here:
            
            PreparedStatement ps;
            ResultSet rs;
            String username = this.user;
            
            String query = "UPDATE `users` SET `Quest`= ? WHERE `username` = ?";
            
            try {
                ps = My_CNX.getConnection().prepareStatement(query);
                ps.setString(1, "academic");
                ps.setString(2, username);
                if((ps.executeUpdate())!=0)
                {
                    JOptionPane.showMessageDialog(null, "Quest selected!");
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(BasicsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            String query_2="SELECT * from`users` where `username` = ?";
            
            
            ps = My_CNX.getConnection().prepareStatement(query_2);
            ps.setString(1, username);
            rs=ps.executeQuery();
            //rs.next();
            String rs1=rs.getString("Quest");
            System.out.println("Quest is "+rs1);
            
            
            this.Quest= "academic";
            buttonPressedNo ++;
            
            if (buttonPressedNo==2)
            {
                jLabeltext.setText("<html>Let's start! <html>");
                jLabelSwordAndShield.setVisible(false);
                jLabelBook.setVisible(true);
                jLabelHeart.setVisible(false);
                jButtonFitness.setVisible(false);
                jButtonAcademic.setVisible(false);
                jButtonMind.setVisible(false);
                jButtonContinue.setVisible(true);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdventureSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAcademicMouseClicked

    private void jButtonMindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMindMouseClicked
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String username = this.user;
        
        String query = "UPDATE `users` SET `Quest`= ? WHERE `username` = ?";      
        
        try {
            ps = My_CNX.getConnection().prepareStatement(query);
            ps.setString(1, "mind");
            ps.setString(2, username);
             if(ps.executeUpdate()!=0)
                     {
                         JOptionPane.showMessageDialog(null, "Quest selected!");                          
                          
                     }
        } catch (SQLException ex) {
            Logger.getLogger(BasicsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.Quest = "mind";
        buttonPressedNo ++;
           
        if (buttonPressedNo==2)
        {
            jLabeltext.setText("<html>Let's start! <html>");
            jLabelSwordAndShield.setVisible(false);
            jLabelBook.setVisible(false);
            jLabelHeart.setVisible(true);
            jButtonFitness.setVisible(false);
            jButtonAcademic.setVisible(false);
            jButtonMind.setVisible(false);
            jButtonContinue.setVisible(true);

        }
    }//GEN-LAST:event_jButtonMindMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdventureSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdventureSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdventureSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdventureSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdventureSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseButton;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JButton jButtonAcademic;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JButton jButtonFitness;
    private javax.swing.JButton jButtonMind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBook;
    private javax.swing.JLabel jLabelHeart;
    private javax.swing.JLabel jLabelSwordAndShield;
    private javax.swing.JLabel jLabeltext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
