/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class BasicsForm extends javax.swing.JFrame {

    /**
     * Creates new form BasicsForm
     */
    private int buttonPressedNo=0;
    private String user;
    private String Class;
    DataUser UserData;
    Login login;
    
    public BasicsForm() {
        initComponents();
        login = new Login();
        setIcon();
        archerLabel.setVisible(false);
        fighterLabel.setVisible(false);
        healerLabel.setVisible(false);
        fighterButton.setVisible(false);
        archerButton.setVisible(false);
        healerButton.setVisible(false);
    }
    
    public void setIcon(){
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/wizard.png")));
    }
    
    public void passData(String user) {
        this.user = user;     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        closeMinPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        wizImg = new javax.swing.JLabel();
        wizardSpeach = new javax.swing.JLabel();
        wizardBallon = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        fighterLabel = new javax.swing.JLabel();
        fighterButton = new javax.swing.JButton();
        healerLabel = new javax.swing.JLabel();
        healerButton = new javax.swing.JButton();
        archerLabel = new javax.swing.JLabel();
        archerButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel2.setLayout(null);

        closeMinPanel.setBackground(new java.awt.Color(153, 102, 0));
        closeMinPanel.setBorder(new javax.swing.border.MatteBorder(null));

        closeButton.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        minimizeButton.setFont(new java.awt.Font("Book Antiqua", 1, 48)); // NOI18N
        minimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        minimizeButton.setText("-");
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closeMinPanelLayout = new javax.swing.GroupLayout(closeMinPanel);
        closeMinPanel.setLayout(closeMinPanelLayout);
        closeMinPanelLayout.setHorizontalGroup(
            closeMinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeMinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        closeMinPanelLayout.setVerticalGroup(
            closeMinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeMinPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(closeMinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel2.add(closeMinPanel);
        closeMinPanel.setBounds(620, 0, 80, 30);

        wizImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wizard2.png"))); // NOI18N
        jPanel2.add(wizImg);
        wizImg.setBounds(20, 80, 120, 130);

        wizardSpeach.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        wizardSpeach.setText("<html> Let's start with the basics. <html>");
        jPanel2.add(wizardSpeach);
        wizardSpeach.setBounds(170, 20, 160, 80);

        wizardBallon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/balloon22.png"))); // NOI18N
        jPanel2.add(wizardBallon);
        wizardBallon.setBounds(140, 0, 240, 130);

        continueButton.setBackground(new java.awt.Color(153, 153, 255));
        continueButton.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        continueButton.setForeground(new java.awt.Color(255, 255, 255));
        continueButton.setText("Continue");
        continueButton.setBorder(new javax.swing.border.MatteBorder(null));
        continueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueButtonMouseClicked(evt);
            }
        });
        jPanel2.add(continueButton);
        continueButton.setBounds(280, 460, 160, 30);

        fighterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fighter.png"))); // NOI18N
        fighterLabel.setText("warrior");
        fighterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fighterLabelMouseClicked(evt);
            }
        });
        jPanel2.add(fighterLabel);
        fighterLabel.setBounds(300, 200, 130, 150);

        fighterButton.setBackground(new java.awt.Color(255, 51, 51));
        fighterButton.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        fighterButton.setForeground(new java.awt.Color(255, 255, 255));
        fighterButton.setText("Fighter");
        fighterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fighterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fighterButtonMouseClicked(evt);
            }
        });
        jPanel2.add(fighterButton);
        fighterButton.setBounds(320, 360, 80, 26);

        healerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/healer.png"))); // NOI18N
        jPanel2.add(healerLabel);
        healerLabel.setBounds(500, 210, 110, 130);

        healerButton.setBackground(new java.awt.Color(204, 255, 255));
        healerButton.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        healerButton.setForeground(new java.awt.Color(255, 255, 255));
        healerButton.setText("Healer");
        healerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        healerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healerButtonMouseClicked(evt);
            }
        });
        jPanel2.add(healerButton);
        healerButton.setBounds(520, 360, 80, 26);

        archerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/archer.png"))); // NOI18N
        jPanel2.add(archerLabel);
        archerLabel.setBounds(120, 210, 110, 130);

        archerButton.setBackground(new java.awt.Color(153, 255, 0));
        archerButton.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        archerButton.setForeground(new java.awt.Color(255, 255, 255));
        archerButton.setText("Archer");
        archerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        archerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archerButtonMouseClicked(evt);
            }
        });
        jPanel2.add(archerButton);
        archerButton.setBounds(130, 360, 80, 26);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tavern.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(7100, 5000));
        background.setMinimumSize(new java.awt.Dimension(700, 500));
        background.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel2.add(background);
        background.setBounds(0, 0, 700, 500);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueButtonMouseClicked
        // TODO add your handling code here:
        buttonPressedNo ++;
        if (buttonPressedNo==1){
            wizardSpeach.setText("<html> Let's pick your class! <html>");
        }
        if (buttonPressedNo==2){
            wizardSpeach.setText("<html>I'm... ahhh lets call it a Wizard!<html>");
            archerLabel.setVisible(true);
            fighterLabel.setVisible(true);
            healerLabel.setVisible(true);
            fighterButton.setVisible(true);
            archerButton.setVisible(true);
            healerButton.setVisible(true);
            continueButton.setVisible(false);
        }
        if (buttonPressedNo==4){
            AdventureSelection ads = new AdventureSelection();
            ads.setVisible(true);
            ads.pack();
            ads.passData(this.user, this.Class, "register");
            ads.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_continueButtonMouseClicked

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void fighterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fighterLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fighterLabelMouseClicked

    private void fighterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fighterButtonMouseClicked
        
        UserData = new DataUser(this.user);
        UserData.updateUserClass("fighter");
        JOptionPane.showMessageDialog(null, "Class selected!");
        this.Class= "fighter";
        buttonPressedNo ++;
        if (buttonPressedNo==3){
            wizardSpeach.setText("<html> A Fighter! I see you've got strength in you! <html>");
            archerButton.setVisible(false);
            healerButton.setVisible(false);
            fighterButton.setVisible(false);
            archerLabel.setVisible(false);
            healerLabel.setVisible(false);
            continueButton.setVisible(true);
        }
                  
    }//GEN-LAST:event_fighterButtonMouseClicked

    private void healerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healerButtonMouseClicked
        
        UserData = new DataUser(this.user);
        UserData.updateUserClass("healer");
        JOptionPane.showMessageDialog(null, "Class selected!");
        this.Class= "healer";
        buttonPressedNo ++;
        if (buttonPressedNo==3){
            wizardSpeach.setText("<html> A Healer! The brave protector of those in need! <html>");
            fighterButton.setVisible(false);
            archerButton.setVisible(false);
            healerButton.setVisible(false);
            fighterLabel.setVisible(false);
            archerLabel.setVisible(false);
            continueButton.setVisible(true);
        }
    }//GEN-LAST:event_healerButtonMouseClicked

    private void archerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archerButtonMouseClicked
        
        UserData = new DataUser(this.user);
        UserData.updateUserClass("archer");
        JOptionPane.showMessageDialog(null, "Class selected!");
        this.Class= "archer";
        buttonPressedNo ++;
        if (buttonPressedNo==3){
            wizardSpeach.setText("<html> An Archer! I can tell you've got keen eyes! <html>");
            fighterButton.setVisible(false);
            archerButton.setVisible(false);
            healerButton.setVisible(false);
            fighterLabel.setVisible(false);
            healerLabel.setVisible(false);
            continueButton.setVisible(true);
        }
    }//GEN-LAST:event_archerButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasicsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archerButton;
    private javax.swing.JLabel archerLabel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel closeButton;
    private javax.swing.JPanel closeMinPanel;
    private javax.swing.JButton continueButton;
    private javax.swing.JButton fighterButton;
    private javax.swing.JLabel fighterLabel;
    private javax.swing.JButton healerButton;
    private javax.swing.JLabel healerLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JLabel wizImg;
    private javax.swing.JLabel wizardBallon;
    private javax.swing.JLabel wizardSpeach;
    // End of variables declaration//GEN-END:variables
}
