/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Gustavo
 */
public class TutorialForm extends javax.swing.JFrame {

    /**
     * Creates new form TutorialForm
     */
    private String user;
    private String password;
    private String Quest;
    private String Class;
    private int flag;
    private int buttonPressedNo=0;
    private int buttonCatNo=0;
    
    public TutorialForm() {
        initComponents();
        setIcon(); 
        JUserButton.setVisible(false);
        UserInfoPanel.setVisible(false);
        jUserImg.setVisible(false);
        jCatImg.setVisible(false);
        jWizRideImg.setVisible(false);
        JWizHouseButton.setVisible(false); 
        jCatalfButton.setVisible(false);
    }
    public void passData(String user, String Quest, String Class) {
        this.user = user;
        this.Quest = Quest;
        this.Class = Class;
      
        if ("fitness".equals(Quest)){
            Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fitnessCenter.png")));
            jLabeltext.setText("<html> Welcome to the Fighters Guild! Here you will be trained to achieve your fitness goal and become a great warrior!<html>");
            flag=1;
        }
        if ("academic".equals(Quest)){
            Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/academicCenter.png")));
            jLabeltext.setText("<html> Welcome the College of Wizardry and Science! Here you will learn from the greatest minds how to achieve academic success!<html>");
            flag=2;
        }
        if ("mind".equals(Quest)){
            Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mindCenter.png")));
            jLabeltext.setText("<html> Welcome to the Arcane Order of the Mind! All the wisemen from our world gather here to seek peace and share their teachings.<html>");
            flag=3;
        }
    }
    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/wizard.png"))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CloseButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabeltext = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonContinue = new javax.swing.JButton();
        jUserImg = new javax.swing.JLabel();
        JUserButton = new javax.swing.JButton();
        UserInfoPanel = new javax.swing.JPanel();
        jLabelMush = new javax.swing.JLabel();
        jLabelExp = new javax.swing.JLabel();
        jLabelCoin = new javax.swing.JLabel();
        jLabelMoney = new javax.swing.JLabel();
        jCatalfButton = new javax.swing.JButton();
        jCatImg = new javax.swing.JLabel();
        JWizHouseButton = new javax.swing.JButton();
        jWizRideImg = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(153, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CloseButton.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        CloseButton.setText("X");
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });

        MinimizeButton.setFont(new java.awt.Font("Book Antiqua", 1, 48)); // NOI18N
        MinimizeButton.setText("-");
        MinimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinimizeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(640, 0, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wizard2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 120, 130);

        jLabeltext.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jPanel1.add(jLabeltext);
        jLabeltext.setBounds(200, 30, 280, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/balloon3.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 10, 370, 130);

        jButtonContinue.setBackground(new java.awt.Color(255, 255, 255));
        jButtonContinue.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jButtonContinue.setText("Continue");
        jButtonContinue.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContinueMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonContinue);
        jButtonContinue.setBounds(220, 413, 220, 30);
        jPanel1.add(jUserImg);
        jUserImg.setBounds(30, 280, 120, 130);

        JUserButton.setBackground(new java.awt.Color(247, 193, 82));
        JUserButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        JUserButton.setForeground(new java.awt.Color(255, 255, 255));
        JUserButton.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(JUserButton);
        JUserButton.setBounds(10, 410, 140, 30);

        UserInfoPanel.setBackground(new java.awt.Color(255, 255, 204));
        UserInfoPanel.setBorder(new javax.swing.border.MatteBorder(null));
        UserInfoPanel.setOpaque(false);

        jLabelMush.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mushies_stage1.png"))); // NOI18N

        jLabelExp.setBackground(new java.awt.Color(255, 204, 51));
        jLabelExp.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabelExp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabelCoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coin.png"))); // NOI18N

        jLabelMoney.setBackground(new java.awt.Color(255, 204, 51));
        jLabelMoney.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabelMoney.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMoney.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout UserInfoPanelLayout = new javax.swing.GroupLayout(UserInfoPanel);
        UserInfoPanel.setLayout(UserInfoPanelLayout);
        UserInfoPanelLayout.setHorizontalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCoin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelExp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMush)
                .addGap(40, 40, 40))
        );
        UserInfoPanelLayout.setVerticalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMush, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(UserInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCoin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabelMoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelExp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(UserInfoPanel);
        UserInfoPanel.setBounds(10, 440, 140, 40);

        jCatalfButton.setBackground(new java.awt.Color(204, 102, 255));
        jCatalfButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jCatalfButton.setForeground(new java.awt.Color(255, 255, 255));
        jCatalfButton.setText("Catalf the Grey");
        jCatalfButton.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jCatalfButton);
        jCatalfButton.setBounds(530, 170, 160, 30);

        jCatImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Catalf.png"))); // NOI18N
        jPanel1.add(jCatImg);
        jCatImg.setBounds(550, 40, 130, 130);

        JWizHouseButton.setBackground(new java.awt.Color(170, 63, 7));
        JWizHouseButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        JWizHouseButton.setForeground(new java.awt.Color(255, 255, 255));
        JWizHouseButton.setText("Wizard House");
        JWizHouseButton.setBorder(new javax.swing.border.MatteBorder(null));
        JWizHouseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JWizHouseButtonMouseClicked(evt);
            }
        });
        jPanel1.add(JWizHouseButton);
        JWizHouseButton.setBounds(530, 410, 160, 30);

        jWizRideImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dragon.png"))); // NOI18N
        jPanel1.add(jWizRideImg);
        jWizRideImg.setBounds(550, 260, 130, 160);

        Background.setBackground(new java.awt.Color(255, 255, 51));
        Background.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 700, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void MinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonMouseClicked

    private void jButtonContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinueMouseClicked
        // TODO add your handling code here:
        buttonPressedNo++;
       
        if (buttonPressedNo==0){
            jLabeltext.setText("<html>Now i'm going to give you a quick guide for your great adventure! <html>");
            System.out.println(user);
            System.out.println(password);
            System.out.println(Quest);
            System.out.println(Class);
            System.out.println("0");
        }
        if (buttonPressedNo==1){
            jLabeltext.setText("<html>Here you can see your character, your username and your points. <html>");
            
            if ("archer".equals(Class)){
                jUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/archer2.png")));
                JUserButton.setText(user+" the "+Class);
            }
            if ("fighter".equals(Class)){
                jUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fighter2.png")));
                JUserButton.setText(user+" the "+Class);  
            }
            if ("healer".equals(Class)){
                jUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/healer2.png")));
                JUserButton.setText(user+" the "+Class);
            }
            JUserButton.setVisible(true);
            UserInfoPanel.setVisible(true);
            jUserImg.setVisible(true);
            System.out.println("1");
        }
        if (buttonPressedNo==2){
            jLabeltext.setText("<html>Over there you can see Catalf the Grey, he's our cat wizard, cat wizards have psychic powers.He can show you other heroes's adventures. <html>");  
            jCatalfButton.setVisible(true);
            jCatImg.setVisible(true);
            System.out.println("2");
        }
        if (buttonPressedNo==3){
            jLabeltext.setText("<html>You can summon him if you ever want to check out how other adventurers's quests are going! <html>");  
            System.out.println("3");
        }
        if (buttonPressedNo==4){
            jLabeltext.setText("<html>You can spend the coins that you received for your hard work in the market! <html>");  
            jWizRideImg.setVisible(true);
            JWizHouseButton.setVisible(true);       
            System.out.println("4");
        }
        if (buttonPressedNo==5){
            jLabeltext.setText("<html>Just press the big red button when you're ready for a new objetive! <html>");  
            System.out.println("5");
        }
        if (buttonPressedNo==6){
            jLabeltext.setText("<html>That's it! Are you ready to start your great adventure? <html>"); 
            jButtonContinue.setText("Let's start!");
            System.out.println("6");
        }
        if(buttonPressedNo == 7){
            GameplayUserHomeForm gmf = new GameplayUserHomeForm();
            gmf.passData(user,"register");
            gmf.setVisible(true);
            gmf.pack();
            gmf.setLocationRelativeTo(null);
            this.dispose();
        }  
    }//GEN-LAST:event_jButtonContinueMouseClicked

    private void JWizHouseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JWizHouseButtonMouseClicked
        GameplayWizardHomeForm WizHomeTravel = new GameplayWizardHomeForm();
        WizHomeTravel.passData(this.user);
        WizHomeTravel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JWizHouseButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorialForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JButton JUserButton;
    private javax.swing.JButton JWizHouseButton;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JPanel UserInfoPanel;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JLabel jCatImg;
    private javax.swing.JButton jCatalfButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCoin;
    private javax.swing.JLabel jLabelExp;
    private javax.swing.JLabel jLabelMoney;
    private javax.swing.JLabel jLabelMush;
    private javax.swing.JLabel jLabeltext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jUserImg;
    private javax.swing.JLabel jWizRideImg;
    // End of variables declaration//GEN-END:variables
}
