/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Gustavo
 */
public class TutorialForm extends javax.swing.JFrame {

    /**
     * Creates new form TutorialForm
     */
    private String user;
    private String password;
    private String Quest;
    private String Class;
    private int flag;
    private int buttonPressedNo=0;
    private int buttonCatNo=0;
    
    public TutorialForm() {
        initComponents();
        setIcon(); 
        jPanel2.setVisible(false);
        jLabelCoin.setVisible(false);
        jLabelMoney.setVisible(false);
        jPanelMoney.setVisible(false);
        jLabelCat.setVisible(false);
        jLabelMarketMan.setVisible(false);
        JbuttonMarket.setVisible(false);
        jButtonCatalf.setVisible(false);
    }
    public void passData(String user, String Quest, String Class) {
        this.user = user;
        this.Quest = Quest;
        this.Class = Class;
      
        if ("fitness".equals(Quest)){
            Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fitnessCenter.png")));
            jLabeltext.setText("<html> Welcome to the Fighters Guild! Here you will be trained to achieve your fitness goal and become a great warrior!<html>");
            flag=1;
        }
        if ("academic".equals(Quest)){
            Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/academicCenter.png")));
            jLabeltext.setText("<html> Welcome the College of Wizardry and Science! Here you will learn from the greatest minds how to achieve academic success!<html>");
            flag=2;
        }
        if ("mind".equals(Quest)){
            Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mindCenter.png")));
            jLabeltext.setText("<html> Welcome to the Arcane Order of the Mind! All the wisemen from our world gather here to seek peace and share their teachings.<html>");
            flag=3;
        }
    }
    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/wizard.png"))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CloseButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabeltext = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonContinue = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabelCharacterImage = new javax.swing.JLabel();
        jPanelMoney = new javax.swing.JPanel();
        jLabelCoin = new javax.swing.JLabel();
        jLabelMoney = new javax.swing.JLabel();
        jLabelCat = new javax.swing.JLabel();
        jButtonCatalf = new javax.swing.JButton();
        jLabelMarketMan = new javax.swing.JLabel();
        JbuttonMarket = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(153, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CloseButton.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        CloseButton.setText("X");
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
        });

        MinimizeButton.setFont(new java.awt.Font("Book Antiqua", 1, 48)); // NOI18N
        MinimizeButton.setText("-");
        MinimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinimizeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(640, 0, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wizard2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 120, 130);

        jLabeltext.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        jPanel1.add(jLabeltext);
        jLabeltext.setBounds(200, 30, 280, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/balloon3.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 10, 370, 130);

        jButtonContinue.setBackground(new java.awt.Color(255, 255, 255));
        jButtonContinue.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jButtonContinue.setText("Continue");
        jButtonContinue.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContinueMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonContinue);
        jButtonContinue.setBounds(220, 413, 220, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        jLabelName.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
            .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 370, 160, 30);
        jPanel1.add(jLabelCharacterImage);
        jLabelCharacterImage.setBounds(30, 240, 120, 130);

        jPanelMoney.setBackground(new java.awt.Color(255, 255, 204));
        jPanelMoney.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coin.png"))); // NOI18N

        jLabelMoney.setBackground(new java.awt.Color(255, 204, 51));
        jLabelMoney.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabelMoney.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMoney.setText("0");

        javax.swing.GroupLayout jPanelMoneyLayout = new javax.swing.GroupLayout(jPanelMoney);
        jPanelMoney.setLayout(jPanelMoneyLayout);
        jPanelMoneyLayout.setHorizontalGroup(
            jPanelMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMoneyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCoin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanelMoneyLayout.setVerticalGroup(
            jPanelMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addComponent(jLabelCoin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelMoney);
        jPanelMoney.setBounds(40, 410, 80, 30);

        jLabelCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Catalf.png"))); // NOI18N
        jPanel1.add(jLabelCat);
        jLabelCat.setBounds(520, 80, 170, 150);

        jButtonCatalf.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCatalf.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jButtonCatalf.setText("Catalf the Grey");
        jButtonCatalf.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonCatalf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCatalfMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCatalf);
        jButtonCatalf.setBounds(520, 240, 160, 30);

        jLabelMarketMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/market.png"))); // NOI18N
        jPanel1.add(jLabelMarketMan);
        jLabelMarketMan.setBounds(560, 280, 90, 160);

        JbuttonMarket.setBackground(new java.awt.Color(255, 255, 255));
        JbuttonMarket.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        JbuttonMarket.setText("Market");
        JbuttonMarket.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(JbuttonMarket);
        JbuttonMarket.setBounds(550, 450, 110, 21);

        Background.setBackground(new java.awt.Color(255, 255, 51));
        Background.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 700, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void MinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonMouseClicked

    private void jButtonContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinueMouseClicked
        // TODO add your handling code here:
         buttonPressedNo++;
       
        if (buttonPressedNo==0)
        {
            jLabeltext.setText("<html>Now i'm going to give you a quick guide for your great adventure! <html>");
            System.out.println(user);
            System.out.println(password);
            System.out.println(Quest);
            System.out.println(Class);
            System.out.println("0");
        }
        if (buttonPressedNo==1)
        {
            jLabeltext.setText("<html>Here you can see your character, your username and your points. <html>");
            
            if ("archer".equals(Class)){
                 jLabelCharacterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/archer2.png")));
                 jLabelName.setText(user+" the "+Class);
                 jPanel2.setVisible(true);
                 jLabelCoin.setVisible(true);
                 jLabelMoney.setVisible(true);
                 jPanelMoney.setVisible(true);
            }
            if ("fighter".equals(Class)){
                 jLabelCharacterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fighter2.png")));
                 jLabelName.setText(user+" the "+Class);
                 jPanel2.setVisible(true);
                 jLabelCoin.setVisible(true);
                 jLabelMoney.setVisible(true);
                 jPanelMoney.setVisible(true);
            }
            if ("healer".equals(Class)){
                 jLabelCharacterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/healer2.png")));
                 jLabelName.setText(user+" the "+Class);
                 jPanel2.setVisible(true);
                 jLabelCoin.setVisible(true);
                 jLabelMoney.setVisible(true);
                 jPanelMoney.setVisible(true);
            }
              
                          System.out.println("1");
        }
        if (buttonPressedNo==2){
            jLabeltext.setText("<html>Over there you can see Catalf the Grey, he's our cat wizard, cat wizards have psychic powers.He can show you other heroes's adventures. <html>");  
            jButtonCatalf.setVisible(true);
            jLabelCat.setVisible(true);
            System.out.println("2");
        }
        if (buttonPressedNo==3){
            jLabeltext.setText("<html>You can summon him if you ever want to check out how other adventurers's quests are going! <html>");  
            System.out.println("3");
        }
         if (buttonPressedNo==4){
            jLabeltext.setText("<html>You can spend the coins that you received for your hard work in the market! <html>");  
            jLabelMarketMan.setVisible(true);
            JbuttonMarket.setVisible(true);       
            System.out.println("4");
        }
         if (buttonPressedNo==5){
            jLabeltext.setText("<html>Just press the big red button when you're ready for a new objetive! <html>");  
            //jButtonChallenge.setVisible(true);
            System.out.println("5");
        }
          if (buttonPressedNo==6){
            jLabeltext.setText("<html>That's it! Are you ready to start your great adventure? <html>"); 
            jButtonContinue.setText("Let's start!");
            System.out.println("6");
        }
           if(buttonPressedNo == 7){
                gameplayForm gmf = new gameplayForm();
                gmf.passData(user,false);
                gmf.setVisible(true);
                gmf.pack();
                gmf.setLocationRelativeTo(null);
                this.dispose();
        }  
    }//GEN-LAST:event_jButtonContinueMouseClicked

    private void jButtonCatalfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCatalfMouseClicked
        // TODO add your handling code here:
       
         
    }//GEN-LAST:event_jButtonCatalfMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorialForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JButton JbuttonMarket;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JButton jButtonCatalf;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCat;
    private javax.swing.JLabel jLabelCharacterImage;
    private javax.swing.JLabel jLabelCoin;
    private javax.swing.JLabel jLabelMarketMan;
    private javax.swing.JLabel jLabelMoney;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabeltext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelMoney;
    // End of variables declaration//GEN-END:variables
}
